services:
  app:
    build: .
    ports:
      - 3000:3000
  postgres:
    restart: on-failure
    image: public.ecr.aws/docker/library/postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - postgres_pgdata:/var/lib/postgresql/data/pgdata
volumes:
  postgres_pgdata: {}
